import Head from 'next/head'
import styles from '../styles/Home.module.css'
import '../styles/Table.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Table Basics</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Table</h1>
    </div>
  )
}
